### ISSUE TITLE
Import Messages from JSON

### ISSUE THREAD

**Issue by brennie** [mozilla/limelight#15]

**Comment by fogha** [comment]
Hello @brennie, I was looking for some first issues to work on, and I realized you have quite a number of issues here. Can I help with a couple

**Comment by brennie** [comment]
Hi @fogha, this is an internal Mozilla tool, so you might not get a lot out of working on it. There are some issues marked ["good first issue"](https://github.com/mozilla/limelight/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) that you could try to take a stab at, however.
